[versions]
junit = "5.10.2"
slf4j = "2.0.13"
logback = "1.5.6"
picocli = "4.7.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.10.2" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
