name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build & Test
        run: ./gradlew clean build --no-daemon --console=plain --stacktrace
